name: Build and release

on:
  push:
    branches:
      main
  workflow_dispatch:
  
jobs:
  build-nativeapp-windows:
    name: Build native app for Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Windows native app
        run: |
          cd native_app_src
          mkdir out
          cmake -B out -G "Visual Studio 17 2022" -A x64
          cmake --build out --config Release
          cd out/x64/Release
          cmake --install ../../
          cd ../../../../
      - uses: actions/upload-artifact@v3
        with:
          name: windows-native-app
          path: native_app/windows/youtube_auto_shutdown_native.exe
        
             
  build-nativeapp-linux:
    name: Build native app for Linux
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v2
      - name: Install Gtk 4
        run: |
          sudo apt-get update
          sudo apt-get install libgtk-4-dev
      - name: Build Linux native app
        run: |
          cd native_app_src
          mkdir out
          cmake -B out -G "Unix Makefiles"
          cmake --build out --config Release
          cd out
          cmake --install ./
          cd ../../
      - uses: actions/upload-artifact@v3
        with:
          name: linux-native-app
          path: native_app/linux/youtube_auto_shutdown_native
             
  publish:
    runs-on: ubuntu-latest
    needs: [build-nativeapp-windows, build-nativeapp-linux]

    steps:
    - uses: actions/checkout@v2
    - name: Create deploy folder (main extension)
      run: mkdir -p ${GITHUB_WORKSPACE}/YoutubeAutoShutdown-Web
    - name: Create native app deploy folder (Windows)
      run: mkdir -p ${GITHUB_WORKSPACE}/YoutubeAutoShutdown-Windows/native_app
    - name: Create native app deploy folder (Linux)
      run: mkdir -p ${GITHUB_WORKSPACE}/YoutubeAutoShutdown-Linux/native_app
      
      
    - name: Copy manifest
      uses: canastro/copy-file-action@master
      with:
        source: "manifest.json"
        target: "YoutubeAutoShutdown-Web/manifest.json"
    - name: Copy icon
      uses: canastro/copy-file-action@master
      with:
        source: "icons"
        target: "YoutubeAutoShutdown-Web/icons"
        flags: "-r"
    - name: Copy JS
      uses: canastro/copy-file-action@master
      with:
        source: "js"
        target: "YoutubeAutoShutdown-Web/js"
        flags: "-r"
    - name: Copy popup
      uses: canastro/copy-file-action@master
      with:
        source: "popup"
        target: "YoutubeAutoShutdown-Web/popup"
        flags: "-r"
        
        
    - name: Download Windows native app
      uses: actions/download-artifact@v3
      with:
        name: windows-native-app
    - name: Copy native manifest for Windows
      uses: canastro/copy-file-action@master
      with:
        source: "native_app/windows"
        target: "YoutubeAutoShutdown-Windows/native_app"
        flags: "-r"
    - name: Copy install script for Windows
      uses: canastro/copy-file-action@master
      with:
        source: "native_app/install_windows.bat"
        target: "YoutubeAutoShutdown-Windows/install.bat"
    - name: Copy uninstall script for Windows
      uses: canastro/copy-file-action@master
      with:
        source: "native_app/uninstall_windows.bat"
        target: "YoutubeAutoShutdown-Windows/uninstall.bat"
    - name: Copy native app for Windows
      uses: canastro/copy-file-action@master
      with:
        source: "youtube_auto_shutdown_native.exe"
        target: "YoutubeAutoShutdown-Windows/native_app/windows/youtube_auto_shutdown_native.exe"
        
        
    - name: Download Linux native app
      uses: actions/download-artifact@v3
      with:
        name: linux-native-app
    - name: Copy native manifest for Linux
      uses: canastro/copy-file-action@master
      with:
        source: "native_app/linux"
        target: "YoutubeAutoShutdown-Linux/native_app"
        flags: "-r"
    - name: Copy install script for Linux
      uses: canastro/copy-file-action@master
      with:
        source: "native_app/install_linux.sh"
        target: "YoutubeAutoShutdown-Linux/install.sh"
    - name: Copy uninstall script for Linux
      uses: canastro/copy-file-action@master
      with:
        source: "native_app/uninstall_linux.sh"
        target: "YoutubeAutoShutdown-Linux/uninstall.sh"   
    - name: Copy native app for Linux
      uses: canastro/copy-file-action@master
      with:
        source: "youtube_auto_shutdown_native"
        target: "YoutubeAutoShutdown-Linux/native_app/linux/youtube_auto_shutdown_native"
    - name: Set native app executable
      run: sudo chmod +x YoutubeAutoShutdown-Linux/native_app/linux/youtube_auto_shutdown_native
    - name: Set install script executable
      run: sudo chmod +x YoutubeAutoShutdown-Linux/install.sh
    - name: Set uninstall script executable
      run: sudo chmod +x YoutubeAutoShutdown-Linux/uninstall.sh
        
    - name: Test
      run: ls ./
      
    - name: Test2
      run: ls YoutubeAutoShutdown-Web/
        
    - name: Zip release (main extension)
      run: zip -qq -r "YoutubeAutoShutdown-WebExtension.zip" YoutubeAutoShutdown-Web
    - name: Zip release (Windows native app)
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r "YoutubeAutoShutdown-NativeApp-Windows.zip" YoutubeAutoShutdown-Windows/*
    - name: Zip release (Linux native app)
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r "YoutubeAutoShutdown-NativeApp-Linux.zip" YoutubeAutoShutdown-Linux/*
    - name: Get release name
      id: release_name
      run: echo "::set-output name=relname::$(date +'Build %Y-%m-%d %H:%M:%S')"
    - name: Get tag name
      id: tag_name
      run: echo "::set-output name=tagname::$(date +'%Y-%m-%d-%H-%M-%S')"
    - name: Create release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "YoutubeAutoShutdown-WebExtension.zip, YoutubeAutoShutdown-NativeApp-Windows.zip, YoutubeAutoShutdown-NativeApp-Linux.zip"
        token: ${{secrets.GITHUB_TOKEN}}
        name: ${{steps.release_name.outputs.relname}}
        tag: ${{steps.tag_name.outputs.tagname}}
        commit: ${{github.sha}}
